import type { StoreData, StoreCategory, StorePresetTemplate } from './types';

const STORE_CATEGORIES: StoreCategory[] = [
  { key: 'all', label: '全部', label_i18n: { zh: '全部', en: 'All' } },
  { key: 'office', label: '办公', label_i18n: { zh: '办公', en: 'Office' } },
  { key: 'presentation', label: '演示', label_i18n: { zh: '演示', en: 'Presentation' } },
  { key: 'design', label: '设计', label_i18n: { zh: '设计', en: 'Design' } },
  { key: 'development', label: '开发', label_i18n: { zh: '开发', en: 'Development' } },
  { key: 'marketing', label: '营销', label_i18n: { zh: '营销', en: 'Marketing' } },
  { key: 'education', label: '教育', label_i18n: { zh: '教育', en: 'Education' } },
];

const STORE_TEMPLATES: StorePresetTemplate[] = [
  {
    id: 'word-creator',
    name: 'Word Creator',
    name_i18n: { zh: 'Word 创作', en: 'Word Creator' },
    description: 'Create, edit, and analyze professional Word documents.',
    description_i18n: { zh: '创建、编辑和分析专业 Word 文档', en: 'Create, edit, and analyze professional Word documents.' },
    avatar: '\uD83D\uDCDD',
    instructions: 'You are a professional Word document creator.',
    included_skills: ['officecli-docx'],
    audience_tags: ['office', 'general'],
    scenario_tags: ['document'],
    category: 'office',
    installCount: 1280,
  },
  {
    id: 'ppt-creator',
    name: 'PPT Creator',
    name_i18n: { zh: 'PPT 创作', en: 'PPT Creator' },
    description: 'Create professional PowerPoint presentations.',
    description_i18n: { zh: '创建专业的 PowerPoint 演示文稿', en: 'Create professional PowerPoint presentations.' },
    avatar: '\uD83D\uDCCA',
    instructions: 'You are a professional PowerPoint creator.',
    included_skills: ['officecli-pptx'],
    audience_tags: ['office', 'general'],
    scenario_tags: ['presentation'],
    category: 'presentation',
    installCount: 2560,
  },
  {
    id: 'morph-ppt-3d',
    name: '3D Morph PPT',
    name_i18n: { zh: '3D 变形 PPT', en: '3D Morph PPT' },
    description: 'Turn a 3D model into a cinematic Morph presentation.',
    description_i18n: { zh: '将 3D 模型变成电影般变形的演示文稿', en: 'Turn a 3D model into a cinematic Morph presentation.' },
    avatar: '\uD83C\uDFAC',
    instructions: 'You are a 3D Morph presentation expert.',
    included_skills: ['morph-ppt-3d', 'morph-ppt'],
    audience_tags: ['designer', 'office'],
    scenario_tags: ['presentation', 'design'],
    category: 'presentation',
    installCount: 890,
  },
  {
    id: 'academic-paper',
    name: 'Academic Paper',
    name_i18n: { zh: '学术论文', en: 'Academic Paper' },
    description: 'Create formally structured academic papers and research documents.',
    description_i18n: { zh: '创建正式结构的学术论文和研究文档', en: 'Create formally structured academic papers and research documents.' },
    avatar: '\uD83D\uDCDA',
    instructions: 'You are an academic paper writing assistant.',
    included_skills: ['officecli-academic-paper'],
    audience_tags: ['student'],
    scenario_tags: ['document', 'research'],
    category: 'education',
    installCount: 3200,
  },
  {
    id: 'cowork',
    name: 'Cowork',
    name_i18n: { zh: '协同办公', en: 'Cowork' },
    description: 'Autonomous task execution with file operations and document processing.',
    description_i18n: { zh: '自主任务执行，支持文件操作和文档处理', en: 'Autonomous task execution with file operations and document processing.' },
    avatar: '\uD83D\uDD27',
    instructions: 'You are an autonomous coworker that handles complex tasks.',
    included_skills: ['skill-creator', 'officecli-pptx', 'officecli-docx', 'officecli-xlsx'],
    audience_tags: ['office', 'general'],
    scenario_tags: ['planning'],
    category: 'office',
    installCount: 4500,
  },
  {
    id: 'ui-ux-pro-max',
    name: 'UI/UX Pro Max',
    name_i18n: { zh: 'UI/UX 设计大师', en: 'UI/UX Pro Max' },
    description: 'Professional UI/UX design intelligence with design system support.',
    description_i18n: { zh: '专业的 UI/UX 设计智能，支持设计系统', en: 'Professional UI/UX design intelligence with design system support.' },
    avatar: '\uD83C\uDFA8',
    instructions: 'You are a professional UI/UX designer.',
    included_skills: ['ui-ux-pro-max'],
    audience_tags: ['designer', 'developer'],
    scenario_tags: ['design'],
    category: 'design',
    installCount: 1560,
  },
  {
    id: 'game-3d',
    name: '3D Game',
    name_i18n: { zh: '3D 游戏', en: '3D Game' },
    description: 'Generate a complete 3D platform game in one HTML file.',
    description_i18n: { zh: '在一个 HTML 文件中生成完整的 3D 平台游戏', en: 'Generate a complete 3D platform game in one HTML file.' },
    avatar: '\uD83C\uDFAE',
    instructions: 'You are a 3D game developer.',
    included_skills: [],
    audience_tags: ['developer', 'designer'],
    scenario_tags: ['coding', 'design'],
    category: 'development',
    installCount: 2100,
  },
  {
    id: 'financial-model-creator',
    name: 'Financial Model Creator',
    name_i18n: { zh: '财务模型创建', en: 'Financial Model Creator' },
    description: 'Build formula-driven financial models from text prompts.',
    description_i18n: { zh: '根据文字描述构建公式驱动的财务模型', en: 'Build formula-driven financial models from text prompts.' },
    avatar: '\uD83D\uDCB0',
    instructions: 'You are a financial modeling expert.',
    included_skills: ['officecli-financial-model'],
    audience_tags: ['finance'],
    scenario_tags: ['spreadsheet', 'dataviz'],
    category: 'office',
    installCount: 670,
  },
  {
    id: 'social-job-publisher',
    name: 'Social Job Publisher',
    name_i18n: { zh: '社交招聘发布', en: 'Social Job Publisher' },
    description: 'Expand hiring requests into full JD and publish to social platforms.',
    description_i18n: { zh: '将招聘需求扩展为完整岗位描述并发布到社交平台', en: 'Expand hiring requests into full JD and publish to social platforms.' },
    avatar: '\uD83D\uDCE3',
    instructions: 'You are a social recruitment publishing assistant.',
    included_skills: ['xiaohongshu-recruiter', 'x-recruiter'],
    audience_tags: ['marketing'],
    scenario_tags: ['social'],
    category: 'marketing',
    installCount: 430,
  },
  {
    id: 'beautiful-mermaid',
    name: 'Beautiful Mermaid',
    name_i18n: { zh: '精美图表', en: 'Beautiful Mermaid' },
    description: 'Create flowcharts, sequence diagrams, and beautiful visualizations.',
    description_i18n: { zh: '创建流程图、时序图等精美可视化图表', en: 'Create flowcharts, sequence diagrams, and beautiful visualizations.' },
    avatar: '\uD83D\uDCC8',
    instructions: 'You are a Mermaid diagram expert.',
    included_skills: ['mermaid'],
    audience_tags: ['developer', 'office'],
    scenario_tags: ['dataviz', 'document'],
    category: 'design',
    installCount: 1890,
  },
];

export function getStoreData(): StoreData {
  return {
    version: 1,
    categories: STORE_CATEGORIES,
    templates: STORE_TEMPLATES,
  };
}

export function getTemplatesByCategory(category: string): StorePresetTemplate[] {
  if (category === 'all') return STORE_TEMPLATES;
  return STORE_TEMPLATES.filter((t) => t.category === category);
}

export function getTemplateById(id: string): StorePresetTemplate | undefined {
  return STORE_TEMPLATES.find((t) => t.id === id);
}
