// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HitIntent } from "./HitIntent";
import type { PresencePointerEvent } from "./PresencePointerEvent";

/**
 * Body for `POST /api/companion/companions/{id}/presence/interact`.
 */
export type ApplyPresenceInteractionRequest = { intent: HitIntent, event: PresencePointerEvent, };
