// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Prompt-cache reuse over provider rounds. Token counts are whole-prompt
 * (fresh + cached). `warm_*` leave out the cold first round of a session.
 */
export type CacheReuseData = { last_round_input_tokens: number, last_round_cache_read_tokens: number, warm_input_tokens: number, warm_cache_read_tokens: number, };
