// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Catalog metadata. Not copied into the overlay runtime install.
 */
export type CompanionPackManifest = { pack_id: string, display_name: string, author?: string | null, license?: string | null, canonical_key?: string | null, };
