// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HitIntent } from "./HitIntent";

/**
 * Hit rectangle in figure-bbox fractions (origin top-left).
 */
export type CompanionHitArea = { id: string, intent: HitIntent, x: number, y: number, w: number, h: number, };
