// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a compaction was triggered (wire mirror of nomi-types CompactTrigger).
 */
export type CompactTriggerData = "auto" | "manual";
