// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a pack draws the figure. CSS packs reuse built-in React characters.
 */
export type CompanionPackRenderer = "css" | "atlas";
