// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompanionAtlasState } from "./CompanionAtlasState";

export type CompanionAtlas = { path: string, cell: [number, number], cols: number, states: Array<CompanionAtlasState>, };
