// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical desktop-companion moods. Unknown stored words fall back to Content.
 */
export type CompanionMood = "happy" | "content" | "sleepy" | "worried" | "excited";
