// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Presence activity. `thinking` is a learn-run in flight; the rest map agent
 * or interaction phases. Built-in CSS characters implement the same ids.
 */
export type CompanionActivity = "idle" | "thinking" | "busy" | "awaiting_user" | "review" | "failed" | "interacting";
