// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One atlas animation row. `id` is an explicit clip name, never inferred from the row index.
 */
export type CompanionAtlasState = { id: string, row: number, frames: number, durations_ms?: Array<number> | null, };
