// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompanionAbcClip } from "./CompanionAbcClip";
import type { CompanionActivity } from "./CompanionActivity";
import type { CompanionAtlas } from "./CompanionAtlas";
import type { CompanionHitArea } from "./CompanionHitArea";
import type { CompanionPackRenderer } from "./CompanionPackRenderer";

/**
 * Host-minimum runtime contract (`runtime.json`).
 */
export type CompanionPackRuntime = { schema_version: number, id: string, display_name: string, renderer: CompanionPackRenderer, atlas?: CompanionAtlas | null, hit_areas: Array<CompanionHitArea>, clips: { [key in string]: CompanionAbcClip }, 
/**
 * Maps AgentExecution / conversation tokens onto presence activities.
 */
agent_bindings: { [key in string]: CompanionActivity }, };
