// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SummarizedConversationPropertiesData } from "./SummarizedConversationPropertiesData";

/**
 * Cursor-style context occupancy categories for one provider request.
 */
export type ContextBreakdownData = { 
system_prompt: number, 
tool_definitions: number, 
rules: number, 
skills: number, 
mcp_and_dynamic_tools: number, 
subagent_definitions: number, 
summarized_conversation: number, 
conversation: number, 
summarized: SummarizedConversationPropertiesData | null, };
