// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Hit-area intent. Table-driven packs bind rectangles to these ids.
 */
export type HitIntent = "head" | "body" | "raise";
