// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ABC interaction phase for a held pointer gesture.
 */
export type InteractionPhase = "idle" | "a_start" | "b_loop" | "c_end";
