// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for the `MoaProgress` event — Mixture-of-Agents fan-out progress
 * (`done` of `total` reference calls finished).
 */
export type MoaProgressEventData = { msg_id: string, done: number, total: number, };
