// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for the `MoaReference` event — one reference model's advisory answer
 * delivered during a Mixture-of-Agents fan-out. `index` is 1-based within
 * `total` configured reference slots.
 */
export type MoaReferenceEventData = { msg_id: string, 
/**
 * Human-readable slot label, typically `"provider_id/model"`.
 */
label: string, 
/**
 * Advice text, or a `"[failed: …]"` sentinel when the slot errored out.
 */
text: string, index: number, total: number, };
