// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One MoA reference slot's usage for the turn. A failed slot reports zero
 * tokens; `cost_usd` is `None` when the catalog price for either side is
 * unknown (tokens are still shown).
 */
export type MoaSlotStatsData = { 
/**
 * Slot label, typically `"provider_id/model"`.
 */
label: string, input_tokens: number, output_tokens: number, 
/**
 * Catalog-priced cost for this slot (USD), `None` when unpriced.
 */
cost_usd: number | null, };
