// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoaSlotStatsData } from "./MoaSlotStatsData";

/**
 * Per-turn Mixture-of-Agents aggregate: one entry per reference slot that
 * was consulted this turn, plus the summed catalog cost when every slot has
 * a known price.
 */
export type MoaTurnStatsData = { slots: Array<MoaSlotStatsData>, 
/**
 * Sum of all known per-slot costs (USD). `None` when no slot has a
 * catalog price (never a partial-looking zero).
 */
total_cost_usd: number | null, };
