// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pointer event reported by the overlay ABC FSM.
 */
export type PresencePointerEvent = "down" | "hold" | "up";
