// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inputs for composing activity from the companion session / AgentExecution.
 */
export type PresenceAgentSnapshot = { learn_running: boolean, conversation_processing: boolean, pending_confirmations: boolean, 
/**
 * `ConversationRuntimeStateKind` snake_case, when known.
 */
runtime_state?: string | null, 
/**
 * `AgentExecutionStatus` snake_case, when a linked execution exists.
 */
execution_status?: string | null, 
/**
 * Work session has this companion summoned (read-only memory; no persona takeover).
 */
summoned: boolean, };
