// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompanionActivity } from "./CompanionActivity";
import type { CompanionMood } from "./CompanionMood";
import type { HitIntent } from "./HitIntent";
import type { InteractionPhase } from "./InteractionPhase";
import type { PresenceStats } from "./PresenceStats";

/**
 * Snapshot the overlay and `/nomi` cards can refetch. WS is a hint only.
 */
export type PresenceState = { stats: PresenceStats, mood: CompanionMood, activity: CompanionActivity, active_clip?: string | null, interaction: InteractionPhase, interaction_intent?: HitIntent | null, last_tick_ms: bigint, last_interact_ms?: bigint | null, };
