// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Normalized 0–100 needs vector. Mood is derived from this, not stored as the
 * sole source of truth.
 */
export type PresenceStats = { energy: number, affection: number, boredom: number, };
