// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for the `ToolPreparing` event.
 */
export type ToolPreparingEventData = { call_id: string, name: string, 
/**
 * Small, already-parsed argument fields such as `file_path` or `command`.
 */
preview: Record<string, unknown> | null, };
