LangString addOrReinstall ${LANG_ENGLISH} "Add/Reinstall components"
LangString alreadyInstalled ${LANG_ENGLISH} "Already Installed"
LangString alreadyInstalledLong ${LANG_ENGLISH} "${PRODUCTNAME} ${VERSION} is already installed. Select the operation you want to perform and click Next to continue."
LangString appRunning ${LANG_ENGLISH} "{{product_name}} is running! Please close it first then try again."
LangString appRunningOkKill ${LANG_ENGLISH} "{{product_name}} is running!$\nClick OK to kill it"
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Choose the maintenance option to perform."
LangString choowHowToInstall ${LANG_ENGLISH} "Choose how you want to install ${PRODUCTNAME}."
LangString createDesktop ${LANG_ENGLISH} "Create desktop shortcut"
LangString dontUninstall ${LANG_ENGLISH} "Do not uninstall"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "Do not uninstall (Downgrading without uninstall is disabled for this installer)"
LangString failedToKillApp ${LANG_ENGLISH} "Failed to kill {{product_name}}. Please close it first then try again"
LangString installingWebview2 ${LANG_ENGLISH} "Installing Microsoft Edge WebView2 Runtime (required by ${PRODUCTNAME})..."
LangString webview2SectionTitle ${LANG_ENGLISH} "Microsoft Edge WebView2 Runtime"
LangString webview2InstallEstimate ${LANG_ENGLISH} "Estimated time: about 1–3 minutes on a typical network (longer on slow links or Windows Server)."
LangString webview2InstallPleaseWait ${LANG_ENGLISH} "Please keep this window open. Progress may look paused while Microsoft downloads components in the background — that is expected."
LangString newerVersionInstalled ${LANG_ENGLISH} "A newer version of ${PRODUCTNAME} is already installed! It is not recommended that you install an older version. If you really want to install this older version, it's better to uninstall the current version first. Select the operation you want to perform and click Next to continue."
LangString older ${LANG_ENGLISH} "older"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "An $R4 version of ${PRODUCTNAME} is installed on your system. It's recommended that you uninstall the current version before installing. Select the operation you want to perform and click Next to continue."
LangString silentDowngrades ${LANG_ENGLISH} "Downgrades are disabled for this installer, can't proceed with the silent installer, please use the graphical interface installer instead.$\n"
LangString unableToUninstall ${LANG_ENGLISH} "Unable to uninstall!"
LangString uninstallApp ${LANG_ENGLISH} "Uninstall ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Uninstall before installing"
LangString unknown ${LANG_ENGLISH} "unknown"
LangString webview2AbortError ${LANG_ENGLISH} "Failed to install Microsoft Edge WebView2 Runtime.$\n$\n${PRODUCTNAME} cannot start without it.$\n$\nPlease check your network, then restart this installer. If it still fails, install WebView2 manually from https://developer.microsoft.com/microsoft-edge/webview2/ and retry.$\n$\nWhen reporting the issue, include this message and your Windows version (e.g. Windows Server 2019)."
LangString webview2DownloadError ${LANG_ENGLISH} "Error: Downloading WebView2 Failed - $0"
LangString webview2DownloadSuccess ${LANG_ENGLISH} "WebView2 bootstrapper downloaded successfully"
LangString webview2Downloading ${LANG_ENGLISH} "Downloading WebView2 bootstrapper…"
LangString webview2InstallError ${LANG_ENGLISH} "Error: Installing WebView2 failed with exit code $1"
LangString webview2InstallSuccess ${LANG_ENGLISH} "WebView2 Runtime installed successfully"
LangString directmlChecking ${LANG_ENGLISH} "Checking Microsoft DirectML (required for on-device audio VAD)…"
LangString directmlAppOk ${LANG_ENGLISH} "DirectML OK: app-local DirectML.dll already exports DMLCreateDevice1."
LangString directmlSystemOk ${LANG_ENGLISH} "DirectML OK: system DirectML.dll already exports DMLCreateDevice1."
LangString directmlNeedRedist ${LANG_ENGLISH} "DirectML on this PC is missing or too old (no DMLCreateDevice1). Will download the Microsoft redistributable."
LangString directmlDownloading ${LANG_ENGLISH} "Downloading Microsoft.AI.DirectML ${DIRECTML_VERSION} from nuget.org…"
LangString directmlDownloadEstimate ${LANG_ENGLISH} "Estimated download: ~18 MB. Typical time: 30 seconds–3 minutes depending on network."
LangString directmlDownloadSource ${LANG_ENGLISH} "Source: ${DIRECTML_NUGET_URL}"
LangString directmlDownloadSuccess ${LANG_ENGLISH} "DirectML package downloaded successfully."
LangString directmlDownloadError ${LANG_ENGLISH} "Error: DirectML download failed — NSISdl status: $0"
LangString directmlExtracting ${LANG_ENGLISH} "Extracting DirectML.dll from the NuGet package…"
LangString directmlExtractError ${LANG_ENGLISH} "Error: Failed to extract DirectML package (tar exit code $0). Is tar.exe available?"
LangString directmlMissingDllError ${LANG_ENGLISH} "Error: DirectML.dll was not found inside the downloaded package (unexpected layout)."
LangString directmlInstalling ${LANG_ENGLISH} "Installing DirectML.dll next to ${PRODUCTNAME}…"
LangString directmlInstallError ${LANG_ENGLISH} "Error: Failed to copy DirectML.dll into the install folder."
LangString directmlVerifyError ${LANG_ENGLISH} "Error: Installed DirectML.dll still lacks DMLCreateDevice1."
LangString directmlInstallSuccess ${LANG_ENGLISH} "DirectML redistributable installed successfully (side-by-side with ${MAINBINARYNAME}.exe)."
LangString directmlAbortError ${LANG_ENGLISH} "Failed to install Microsoft DirectML.$\n$\n${PRODUCTNAME} cannot start without DirectML.dll exporting DMLCreateDevice1.$\n$\nPlease check network access to nuget.org, then restart this installer.$\n$\nWhen reporting the issue, screenshot this dialog and include your Windows version (e.g. Windows Server 2019 17763)."
LangString deleteAppData ${LANG_ENGLISH} "Delete the application data"
