LangString addOrReinstall ${LANG_SIMPCHINESE} "添加/重新安装组件"
LangString alreadyInstalled ${LANG_SIMPCHINESE} "已安装"
LangString alreadyInstalledLong ${LANG_SIMPCHINESE} "${PRODUCTNAME} ${VERSION} 已经安装了。选择你想要执行的操作后点击下一步以继续。"
LangString appRunning ${LANG_SIMPCHINESE} "{{product_name}} 正在运行！请关闭后再试。"
LangString appRunningOkKill ${LANG_SIMPCHINESE} "{{product_name}} 正在运行！$\n点击确定以终止运行。"
LangString chooseMaintenanceOption ${LANG_SIMPCHINESE} "选择要执行的维护操作。"
LangString choowHowToInstall ${LANG_SIMPCHINESE} "选择你想要安装 ${PRODUCTNAME} 的方式。"
LangString createDesktop ${LANG_SIMPCHINESE} "创建桌面快捷方式"
LangString dontUninstall ${LANG_SIMPCHINESE} "请勿卸载"
LangString dontUninstallDowngrade ${LANG_SIMPCHINESE} "请勿卸载（此安装程序禁止未卸载就进行版本降级的操作）"
LangString failedToKillApp ${LANG_SIMPCHINESE} "无法终止 {{product_name}}。请关闭后再试。"
LangString installingWebview2 ${LANG_SIMPCHINESE} "正在安装 Microsoft Edge WebView2 运行时（${PRODUCTNAME} 必需组件）..."
LangString webview2SectionTitle ${LANG_SIMPCHINESE} "Microsoft Edge WebView2 运行时"
LangString webview2InstallEstimate ${LANG_SIMPCHINESE} "预计耗时：常见网络约 1–3 分钟（网速较慢或 Windows Server 可能更久）。"
LangString webview2InstallPleaseWait ${LANG_SIMPCHINESE} "请保持本窗口打开。安装过程中进度可能看似停住——此时微软组件仍在后台下载，属正常现象。"
LangString newerVersionInstalled ${LANG_SIMPCHINESE} "有一个更新版本的 ${PRODUCTNAME} 已经安装了！不推荐你安装旧的版本。如果你真的想要安装这个旧的版本，推荐先卸载当前版本。选择你想要执行的操作后点击下一步以继续。"
LangString older ${LANG_SIMPCHINESE} "旧的"
LangString olderOrUnknownVersionInstalled ${LANG_SIMPCHINESE} "系统中已存在版本为 $R4 的 ${PRODUCTNAME}。推荐先卸载当前版本后再进行安装。选择你想要执行的操作后点击下一步以继续。"
LangString silentDowngrades ${LANG_SIMPCHINESE} "降级操作在此安装程序上已禁用，无法进行安静安装，请使用图形操作界面。$\n"
LangString unableToUninstall ${LANG_SIMPCHINESE} "无法卸载！"
LangString uninstallApp ${LANG_SIMPCHINESE} "卸载 ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_SIMPCHINESE} "安装前卸载"
LangString unknown ${LANG_SIMPCHINESE} "未知"
LangString webview2AbortError ${LANG_SIMPCHINESE} "无法安装 Microsoft Edge WebView2 运行时。$\n$\n没有它，${PRODUCTNAME} 无法启动。$\n$\n请检查网络后重新运行本安装程序。若仍然失败，请先从 https://developer.microsoft.com/microsoft-edge/webview2/ 手动安装 WebView2，再重试。$\n$\n反馈问题时请附上本提示，以及 Windows 版本（例如 Windows Server 2019）。"
LangString webview2DownloadError ${LANG_SIMPCHINESE} "错误：无法下载 WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_SIMPCHINESE} "WebView2 引导程序下载成功"
LangString webview2Downloading ${LANG_SIMPCHINESE} "正在下载 WebView2 引导程序…"
LangString webview2InstallError ${LANG_SIMPCHINESE} "错误：安装 WebView2 失败，退出码：$1"
LangString webview2InstallSuccess ${LANG_SIMPCHINESE} "WebView2 运行时安装成功"
LangString directmlChecking ${LANG_SIMPCHINESE} "正在检查 Microsoft DirectML（本地音频 VAD 需要）…"
LangString directmlAppOk ${LANG_SIMPCHINESE} "DirectML 正常：安装目录中的 DirectML.dll 已包含 DMLCreateDevice1。"
LangString directmlSystemOk ${LANG_SIMPCHINESE} "DirectML 正常：系统 DirectML.dll 已包含 DMLCreateDevice1。"
LangString directmlNeedRedist ${LANG_SIMPCHINESE} "本机 DirectML 缺失或过旧（无 DMLCreateDevice1）。将下载微软官方可再发行包。"
LangString directmlDownloading ${LANG_SIMPCHINESE} "正在从 nuget.org 下载 Microsoft.AI.DirectML ${DIRECTML_VERSION}…"
LangString directmlDownloadEstimate ${LANG_SIMPCHINESE} "预计下载约 18 MB；常见网络约 30 秒–3 分钟。"
LangString directmlDownloadSource ${LANG_SIMPCHINESE} "下载地址：${DIRECTML_NUGET_URL}"
LangString directmlDownloadSuccess ${LANG_SIMPCHINESE} "DirectML 安装包下载成功。"
LangString directmlDownloadError ${LANG_SIMPCHINESE} "错误：DirectML 下载失败 — NSISdl 状态：$0"
LangString directmlExtracting ${LANG_SIMPCHINESE} "正在从 NuGet 包中解压 DirectML.dll…"
LangString directmlExtractError ${LANG_SIMPCHINESE} "错误：解压 DirectML 失败（tar 退出码 $0）。请确认系统有 tar.exe。"
LangString directmlMissingDllError ${LANG_SIMPCHINESE} "错误：下载的包内未找到 DirectML.dll（包结构异常）。"
LangString directmlInstalling ${LANG_SIMPCHINESE} "正在将 DirectML.dll 安装到 ${PRODUCTNAME} 目录…"
LangString directmlInstallError ${LANG_SIMPCHINESE} "错误：无法将 DirectML.dll 复制到安装目录。"
LangString directmlVerifyError ${LANG_SIMPCHINESE} "错误：安装后的 DirectML.dll 仍缺少 DMLCreateDevice1。"
LangString directmlInstallSuccess ${LANG_SIMPCHINESE} "DirectML 可再发行组件安装成功（与 ${MAINBINARYNAME}.exe 同目录）。"
LangString directmlAbortError ${LANG_SIMPCHINESE} "无法安装 Microsoft DirectML。$\n$\n没有导出 DMLCreateDevice1 的 DirectML.dll，${PRODUCTNAME} 无法启动。$\n$\n请检查能否访问 nuget.org，然后重新运行本安装程序。$\n$\n反馈问题时请截图本对话框，并注明 Windows 版本（例如 Windows Server 2019 17763）。"
LangString deleteAppData ${LANG_SIMPCHINESE} "删除应用程序数据"
